// ======================================================================
// \title  SignalPairSerializableAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for SignalPair struct
// ======================================================================

#ifndef Ref_SignalPairSerializableAc_HPP
#define Ref_SignalPairSerializableAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Ref {

  class SignalPair :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE =
          sizeof(F32) +
          sizeof(F32)
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value)
      SignalPair();

      //! Member constructor
      SignalPair(
          F32 time,
          F32 value
      );

      //! Copy constructor
      SignalPair(
          const SignalPair& obj //!< The source object
      );

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator
      SignalPair& operator=(
          const SignalPair& obj //!< The source object
      );

      //! Equality operator
      bool operator==(
          const SignalPair& obj //!< The other object
      ) const;

      //! Inequality operator
      bool operator!=(
          const SignalPair& obj //!< The other object
      ) const;

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const SignalPair& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Serialization
      Fw::SerializeStatus serializeTo(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialization
      Fw::SerializeStatus deserializeFrom(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

      //! Get the dynamic serialized size of the struct
      FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

      //! Convert struct to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

      // ----------------------------------------------------------------------
      // Getter functions
      // ----------------------------------------------------------------------

      //! Get member time
      F32 get_time() const
      {
        return this->m_time;
      }

      //! Get member value
      F32 get_value() const
      {
        return this->m_value;
      }

      // ----------------------------------------------------------------------
      // Setter functions
      // ----------------------------------------------------------------------

      //! Set all members
      void set(
          F32 time,
          F32 value
      );

      //! Set member time
      void set_time(F32 time);

      //! Set member value
      void set_value(F32 value);

    protected:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      F32 m_time;
      F32 m_value;

  };

}

#endif
