// ======================================================================
// \title  Ref_RefPacketsTlmPacketsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for RefPackets telemetry packets
// ======================================================================

#ifndef Ref_Ref_RefPacketsTlmPackets_HPP
#define Ref_Ref_RefPacketsTlmPackets_HPP

#include "Svc/TlmPacketizer/TlmPacketizerTypes.hpp"

namespace Ref {

  namespace Ref_RefPacketsTlmPackets {

    // ----------------------------------------------------------------------
    // Extern variables
    // ----------------------------------------------------------------------

    //! The list of packets
    extern const Svc::TlmPacketizerPacketList packetList;

    //! The omitted channels
    extern const Svc::TlmPacketizerPacket omittedChannels;

  }

}

#endif
