// ======================================================================
// \title  DpDemo_ArrayOfStructsArrayAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DpDemo_ArrayOfStructs array
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "Ref/DpDemo/DpDemo_ArrayOfStructsArrayAc.hpp"

namespace Ref {

  // ----------------------------------------------------------------------
  // Constructors
  // ----------------------------------------------------------------------

  DpDemo_ArrayOfStructs ::
    DpDemo_ArrayOfStructs() :
      Serializable()
  {
    // Construct using element-wise constructor
    *this = DpDemo_ArrayOfStructs(
      Ref::DpDemo_StructWithStringMembers(Fw::String(""), Ref::DpDemo_StringArray(Fw::String(""), Fw::String(""))),
      Ref::DpDemo_StructWithStringMembers(Fw::String(""), Ref::DpDemo_StringArray(Fw::String(""), Fw::String(""))),
      Ref::DpDemo_StructWithStringMembers(Fw::String(""), Ref::DpDemo_StringArray(Fw::String(""), Fw::String("")))
    );
  }

  DpDemo_ArrayOfStructs ::
    DpDemo_ArrayOfStructs(const ElementType (&a)[SIZE]) :
      Serializable()
  {
    for (U32 index = 0; index < SIZE; index++) {
      this->elements[index] = a[index];
    }
  }

  DpDemo_ArrayOfStructs ::
    DpDemo_ArrayOfStructs(const ElementType& e) :
      Serializable()
  {
    for (U32 index = 0; index < SIZE; index++) {
      this->elements[index] = e;
    }
  }

  DpDemo_ArrayOfStructs ::
    DpDemo_ArrayOfStructs(
        const ElementType& e1,
        const ElementType& e2,
        const ElementType& e3
    ) :
      Serializable()
  {
    this->elements[0] = e1;
    this->elements[1] = e2;
    this->elements[2] = e3;
  }

  DpDemo_ArrayOfStructs ::
    DpDemo_ArrayOfStructs(const DpDemo_ArrayOfStructs& obj) :
      Serializable()
  {
    for (U32 index = 0; index < SIZE; index++) {
      this->elements[index] = obj.elements[index];
    }
  }

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  DpDemo_ArrayOfStructs::ElementType& DpDemo_ArrayOfStructs ::
    operator[](const U32 i)
  {
    FW_ASSERT(i < SIZE, static_cast<FwAssertArgType>(i), static_cast<FwAssertArgType>(SIZE));
    return this->elements[i];
  }

  const DpDemo_ArrayOfStructs::ElementType& DpDemo_ArrayOfStructs ::
    operator[](const U32 i) const
  {
    FW_ASSERT(i < SIZE, static_cast<FwAssertArgType>(i), static_cast<FwAssertArgType>(SIZE));
    return this->elements[i];
  }

  DpDemo_ArrayOfStructs& DpDemo_ArrayOfStructs ::
    operator=(const DpDemo_ArrayOfStructs& obj)
  {
    if (this == &obj) {
      return *this;
    }

    for (U32 index = 0; index < SIZE; index++) {
      this->elements[index] = obj.elements[index];
    }
    return *this;
  }

  DpDemo_ArrayOfStructs& DpDemo_ArrayOfStructs ::
    operator=(const ElementType (&a)[SIZE])
  {
    for (U32 index = 0; index < SIZE; index++) {
      this->elements[index] = a[index];
    }
    return *this;
  }

  DpDemo_ArrayOfStructs& DpDemo_ArrayOfStructs ::
    operator=(const ElementType& e)
  {
    for (U32 index = 0; index < SIZE; index++) {
      this->elements[index] = e;
    }
    return *this;
  }

  bool DpDemo_ArrayOfStructs ::
    operator==(const DpDemo_ArrayOfStructs& obj) const
  {
    for (U32 index = 0; index < SIZE; index++) {
      if (!((*this)[index] == obj[index])) {
        return false;
      }
    }
    return true;
  }

  bool DpDemo_ArrayOfStructs ::
    operator!=(const DpDemo_ArrayOfStructs& obj) const
  {
    return !(*this == obj);
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const DpDemo_ArrayOfStructs& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Public member functions
  // ----------------------------------------------------------------------

  Fw::SerializeStatus DpDemo_ArrayOfStructs ::
    serializeTo(Fw::SerializeBufferBase& buffer) const
  {
    Fw::SerializeStatus status = Fw::FW_SERIALIZE_OK;
    for (U32 index = 0; index < SIZE; index++) {
      status = buffer.serializeFrom((*this)[index]);
      if (status != Fw::FW_SERIALIZE_OK) {
        return status;
      }
    }
    return status;
  }

  Fw::SerializeStatus DpDemo_ArrayOfStructs ::
    deserializeFrom(Fw::SerializeBufferBase& buffer)
  {
    Fw::SerializeStatus status = Fw::FW_SERIALIZE_OK;
    for (U32 index = 0; index < SIZE; index++) {
      status = buffer.deserializeTo((*this)[index]);
      if (status != Fw::FW_SERIALIZE_OK) {
        return status;
      }
    }
    return status;
  }

  FwSizeType DpDemo_ArrayOfStructs ::
    serializedSize() const
  {
    FwSizeType size = 0;
    for (U32 index = 0; index < SIZE; index++) {
      size += this->elements[index].serializedSize();
    }
    return size;
  }

#if FW_SERIALIZABLE_TO_STRING

  void DpDemo_ArrayOfStructs ::
    toString(Fw::StringBase& sb) const
  {
    // Clear the output string
    sb = "";

    // Array prefix
    if (sb.length() + 2 <= sb.maxLength()) {
      sb += "[ ";
    } else {
      return;
    }

    for (U32 index = 0; index < SIZE; index++) {
      Fw::String tmp;
      this->elements[index].toString(tmp);

      FwSizeType size = tmp.length() + (index > 0 ? 2 : 0);
      if ((size + sb.length()) <= sb.maxLength()) {
        if (index > 0) {
          sb += ", ";
        }
        sb += tmp;
      } else {
        break;
      }
    }

    // Array suffix
    if (sb.length() + 2 <= sb.maxLength()) {
      sb += " ]";
    }
  }

#endif

}
