// ======================================================================
// \title  DpDemo_BoolAliasAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for DpDemo_BoolAlias alias
// ======================================================================

#ifndef Ref_DpDemo_DpDemo_BoolAliasAliasAc_HPP
#define Ref_DpDemo_DpDemo_BoolAliasAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"

namespace Ref {

  using DpDemo_BoolAlias = bool;

}

#endif
