// ======================================================================
// \title  DpDemo_ColorInfoStructSerializableAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for DpDemo_ColorInfoStruct struct
// ======================================================================

#ifndef Ref_DpDemo_DpDemo_ColorInfoStructSerializableAc_HPP
#define Ref_DpDemo_DpDemo_ColorInfoStructSerializableAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"
#include "Ref/DpDemo/DpDemo_ColorEnumEnumAc.hpp"

namespace Ref {

  class DpDemo_ColorInfoStruct :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE =
          Ref::DpDemo_ColorEnum::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value)
      DpDemo_ColorInfoStruct();

      //! Member constructor
      DpDemo_ColorInfoStruct(Ref::DpDemo_ColorEnum::T Color);

      //! Copy constructor
      DpDemo_ColorInfoStruct(
          const DpDemo_ColorInfoStruct& obj //!< The source object
      );

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator
      DpDemo_ColorInfoStruct& operator=(
          const DpDemo_ColorInfoStruct& obj //!< The source object
      );

      //! Equality operator
      bool operator==(
          const DpDemo_ColorInfoStruct& obj //!< The other object
      ) const;

      //! Inequality operator
      bool operator!=(
          const DpDemo_ColorInfoStruct& obj //!< The other object
      ) const;

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const DpDemo_ColorInfoStruct& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Serialization
      Fw::SerializeStatus serializeTo(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialization
      Fw::SerializeStatus deserializeFrom(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

      //! Get the dynamic serialized size of the struct
      FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

      //! Convert struct to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

      // ----------------------------------------------------------------------
      // Getter functions
      // ----------------------------------------------------------------------

      //! Get member Color
      Ref::DpDemo_ColorEnum::T get_Color() const
      {
        return this->m_Color.e;
      }

      // ----------------------------------------------------------------------
      // Setter functions
      // ----------------------------------------------------------------------

      //! Set all members
      void set(Ref::DpDemo_ColorEnum::T Color);

      //! Set member Color
      void set_Color(Ref::DpDemo_ColorEnum::T Color);

    protected:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      Ref::DpDemo_ColorEnum m_Color;

  };

}

#endif
