// ======================================================================
// \title  DpDemo_BooleanArrayArrayAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for DpDemo_BooleanArray array
// ======================================================================

#ifndef Ref_DpDemo_DpDemo_BooleanArrayArrayAc_HPP
#define Ref_DpDemo_DpDemo_BooleanArrayArrayAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Ref {

  //! Array of booleans
  class DpDemo_BooleanArray :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The element type
      using ElementType = bool;

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the array
        SIZE = 2,
        //! The serialized size of each element
        ELEMENT_SERIALIZED_SIZE = sizeof(U8),
        //! The size of the serial representation
        SERIALIZED_SIZE = SIZE * ELEMENT_SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value)
      DpDemo_BooleanArray();

      //! Constructor (user-provided value)
      DpDemo_BooleanArray(
          const ElementType (&a)[SIZE] //!< The array
      );

      //! Constructor (single element)
      DpDemo_BooleanArray(
          const ElementType& e //!< The element
      );

      //! Constructor (multiple elements)
      DpDemo_BooleanArray(
          const ElementType& e1, //!< Element 1
          const ElementType& e2 //!< Element 2
      );

      //! Copy Constructor
      DpDemo_BooleanArray(
          const DpDemo_BooleanArray& obj //!< The source object
      );

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Subscript operator
      ElementType& operator[](
          const U32 i //!< The subscript index
      );

      //! Const subscript operator
      const ElementType& operator[](
          const U32 i //!< The subscript index
      ) const;

      //! Copy assignment operator (object)
      DpDemo_BooleanArray& operator=(
          const DpDemo_BooleanArray& obj //!< The source object
      );

      //! Copy assignment operator (raw array)
      DpDemo_BooleanArray& operator=(
          const ElementType (&a)[SIZE] //!< The source array
      );

      //! Copy assignment operator (single element)
      DpDemo_BooleanArray& operator=(
          const ElementType& e //!< The element
      );

      //! Equality operator
      bool operator==(
          const DpDemo_BooleanArray& obj //!< The other object
      ) const;

      //! Inequality operator
      bool operator!=(
          const DpDemo_BooleanArray& obj //!< The other object
      ) const;

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const DpDemo_BooleanArray& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Public member functions
      // ----------------------------------------------------------------------

      //! Serialization
      Fw::SerializeStatus serializeTo(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialization
      Fw::SerializeStatus deserializeFrom(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

      //! Get the dynamic serialized size of the array
      FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

      //! Convert array to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The array elements
      ElementType elements[SIZE];

  };

}

#endif
