// ======================================================================
// \title  DpDemo_ColorEnumEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DpDemo_ColorEnum enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "Ref/DpDemo/DpDemo_ColorEnumEnumAc.hpp"

namespace Ref {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  DpDemo_ColorEnum& DpDemo_ColorEnum ::
    operator=(const DpDemo_ColorEnum& obj)
  {
    this->e = obj.e;
    return *this;
  }

  DpDemo_ColorEnum& DpDemo_ColorEnum ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const DpDemo_ColorEnum& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool DpDemo_ColorEnum ::
    isValid() const
  {
    return ((e >= RED) && (e <= BLUE));
  }

  Fw::SerializeStatus DpDemo_ColorEnum ::
    serializeTo(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serializeFrom(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus DpDemo_ColorEnum ::
    deserializeFrom(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserializeTo(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void DpDemo_ColorEnum ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case RED:
        s = "RED";
        break;
      case GREEN:
        s = "GREEN";
        break;
      case BLUE:
        s = "BLUE";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void DpDemo_ColorEnum ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
