// ======================================================================
// \title  DpDemo_I32AliasAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for DpDemo_I32Alias alias
// ======================================================================

#ifndef Ref_DpDemo_DpDemo_I32AliasAliasAc_HPP
#define Ref_DpDemo_DpDemo_I32AliasAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"

namespace Ref {

  using DpDemo_I32Alias = I32;

}

#endif
