// ======================================================================
// \title  EventManager_EnabledEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for EventManager_Enabled enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "Svc/EventManager/EventManager_EnabledEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  EventManager_Enabled& EventManager_Enabled ::
    operator=(const EventManager_Enabled& obj)
  {
    this->e = obj.e;
    return *this;
  }

  EventManager_Enabled& EventManager_Enabled ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const EventManager_Enabled& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool EventManager_Enabled ::
    isValid() const
  {
    return ((e >= ENABLED) && (e <= DISABLED));
  }

  Fw::SerializeStatus EventManager_Enabled ::
    serializeTo(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serializeFrom(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus EventManager_Enabled ::
    deserializeFrom(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserializeTo(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void EventManager_Enabled ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case ENABLED:
        s = "ENABLED";
        break;
      case DISABLED:
        s = "DISABLED";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void EventManager_Enabled ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
