// ======================================================================
// \title  PacketStatSerializableAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for PacketStat struct
// ======================================================================

#ifndef Ref_PacketStatSerializableAc_HPP
#define Ref_PacketStatSerializableAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"
#include "Ref/RecvBuffApp/PacketRecvStatusEnumAc.hpp"

namespace Ref {

  //! Some Packet Statistics
  class PacketStat :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE =
          sizeof(U32) +
          sizeof(U32) +
          Ref::PacketRecvStatus::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value)
      PacketStat();

      //! Member constructor
      PacketStat(
          U32 BuffRecv,
          U32 BuffErr,
          Ref::PacketRecvStatus::T PacketStatus
      );

      //! Copy constructor
      PacketStat(
          const PacketStat& obj //!< The source object
      );

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator
      PacketStat& operator=(
          const PacketStat& obj //!< The source object
      );

      //! Equality operator
      bool operator==(
          const PacketStat& obj //!< The other object
      ) const;

      //! Inequality operator
      bool operator!=(
          const PacketStat& obj //!< The other object
      ) const;

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const PacketStat& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Serialization
      Fw::SerializeStatus serializeTo(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialization
      Fw::SerializeStatus deserializeFrom(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

      //! Get the dynamic serialized size of the struct
      FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

      //! Convert struct to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

      // ----------------------------------------------------------------------
      // Getter functions
      // ----------------------------------------------------------------------

      //! Get member BuffRecv
      U32 get_BuffRecv() const
      {
        return this->m_BuffRecv;
      }

      //! Get member BuffErr
      U32 get_BuffErr() const
      {
        return this->m_BuffErr;
      }

      //! Get member PacketStatus
      Ref::PacketRecvStatus::T get_PacketStatus() const
      {
        return this->m_PacketStatus.e;
      }

      // ----------------------------------------------------------------------
      // Setter functions
      // ----------------------------------------------------------------------

      //! Set all members
      void set(
          U32 BuffRecv,
          U32 BuffErr,
          Ref::PacketRecvStatus::T PacketStatus
      );

      //! Set member BuffRecv
      void set_BuffRecv(U32 BuffRecv);

      //! Set member BuffErr
      void set_BuffErr(U32 BuffErr);

      //! Set member PacketStatus
      void set_PacketStatus(Ref::PacketRecvStatus::T PacketStatus);

    protected:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      U32 m_BuffRecv;
      U32 m_BuffErr;
      Ref::PacketRecvStatus m_PacketStatus;

  };

}

#endif
