// ======================================================================
// \title  Ports_ComBufferQueueEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Ports_ComBufferQueue enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "Svc/Subtopologies/ComCcsds/Ports_ComBufferQueueEnumAc.hpp"

namespace ComCcsds {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  Ports_ComBufferQueue& Ports_ComBufferQueue ::
    operator=(const Ports_ComBufferQueue& obj)
  {
    this->e = obj.e;
    return *this;
  }

  Ports_ComBufferQueue& Ports_ComBufferQueue ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const Ports_ComBufferQueue& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool Ports_ComBufferQueue ::
    isValid() const
  {
    return ((e >= FILE) && (e <= FILE));
  }

  Fw::SerializeStatus Ports_ComBufferQueue ::
    serializeTo(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serializeFrom(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus Ports_ComBufferQueue ::
    deserializeFrom(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserializeTo(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void Ports_ComBufferQueue ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case FILE:
        s = "FILE";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void Ports_ComBufferQueue ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
