site_name: F Prime
site_url: https://fprime.jpl.nasa.gov/
repo_url: https://github.com/nasa/fprime
repo_name: nasa/fprime
docs_dir: .. # using ./fprime/ as the root directory to host all source files in the website
site_dir: ../../site
edit_uri: edit/devel/ # for "Edit Source" button (see content.action.edit)

exclude_docs: |
  Autocoders/
  ci/
  googletest/

theme:
  name: material # enables the material theme, DO NOT CHANGE
  language: en
  logo: assets/images/logo-fprime-jpl.svg
  favicon: assets/images/favicon.svg
  custom_dir: ../../overrides # external directory
  icon:
    annotation: material/information-slab-circle  # custom icon for annotations

  features:
    - navigation.tabs # enables tabs
    - navigation.top # enables back to top button
    - navigation.tabs.sticky # makes tabs sticky
    # - navigation.expand # expands all navigation links with dropdowns by default
    - navigation.footer # enables previous/next page navigation links by the footer
    - navigation.instant # instant loading
    - navigation.indexes # enables overview pages for sections
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - content.code.copy # enable code copy for all code blocks
    - content.code.annotate # enable code annotations for all code blocks
    - content.tooltips # replaces the browser's rendering logic for title attribute with tooltips (for content, header, navigation)
    - content.tabs.link # all content tabs across the whole documentation site will be linked and switch to the same label when the user clicks on a tab
    - content.action.edit # display a "Edit Source" button on the top right of the page

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-off
        name: Switch to light mode



# Adds extra settings
extra:
  version:
      provider: mike
      alias: true
  generator: false # removes "Made with Material for Mkdocs"
  homepage: https://fprime.jpl.nasa.gov/ # Forces homepage link not to include versioning info



# Link to custom css
extra_css:
  - assets/stylesheets/extra.css

# Adds material for mkdocs plugins
plugins:
  - search # enables search
  - awesome-nav
  - mike:
      # symlink are not allowed in GH Pages so if website needs to be deployed on GH Pages, use `copy` instead
      # see https://github.blog/changelog/2023-02-21-github-pages-deprecating-symlinks-in-non-actions-builds/
      alias_type: symlink
      canonical_version: latest
  - open-in-new-tab
  - multirepo:
      cleanup: true
      nav_repos:
        - name: tutorials-hello-world
          import_url: https://github.com/fprime-community/fprime-tutorial-hello-world?branch=devel
          imports: [
            docs/hello-world.md
          ]
        - name: tutorials-led-blinker
          import_url: https://github.com/fprime-community/fprime-workshop-led-blinker?branch=devel
          imports: [
            docs/led-blinker.md,
            docs/hardware.md
            docs/img
          ]
        - name: tutorials-math-component
          import_url: https://github.com/fprime-community/fprime-tutorial-math-component?branch=devel
          imports: [
            docs/math-component.md
            docs/img
          ]
        - name: tutorials-arduino-led-blinker
          import_url: https://github.com/fprime-community/fprime-tutorial-arduino-blinker?branch=main
          imports: [
            docs/arduino-led-blinker.md,
            docs/img
          ]


markdown_extensions: 
  - toc:
      toc_depth: 2
  - attr_list # allows to add HTML attributes and CSS classes to almost every Markdown inline- and block-level element with a special syntax
  - md_in_html # allows for writing Markdown inside of HTML
  - tables # enables markdown tables
  # enables syntax highlighting on code blocks and inline code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # adds support for admonitions/call-outs
  - admonition
  - pymdownx.details
  - github-callouts # enables GitHub-style Markdown alerts (e.g. > [!NOTE])
  # enables the use of definition lists and tasks lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # enables abbreviations and allows to build a simple project-wide glossary, sourcing definitions from a central location.
  - abbr
  - pymdownx.snippets
  # enables tabs
  - pymdownx.tabbed:
      alternate_style: true
  # enables the use of icons and emojis by using simple shortcodes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# Custom navigation is set in the fprime/.nav.yml file
# Must keep a copy of just the tutorials nav here to let multirepo know to import them, this does not act as a nav
nav:
  - Tutorials:
    - Tutorials Index: docs/tutorials/index.md
    - 'Hello World': tutorials-hello-world/docs/hello-world.md
    - 'LED Blinker': tutorials-led-blinker/docs/led-blinker.md
    - 'MathComponent': tutorials-math-component/docs/math-component.md
    - 'Cross-Compilation Setup': docs/tutorials/cross-compilation.md
    - 'Arduino LED Blinker': tutorials-arduino-led-blinker/docs/arduino-led-blinker.md
