name: "FppTest"

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

jobs:
  fpptest:
    name: Run FppTest
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout F´ Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: "Install requirements.txt"
        run: |
          pip3 install -r ./requirements.txt
        shell: bash
      - name: "Generate UT build cache"
        working-directory: ./FppTestProject
        run: |
          fprime-util generate --ut
        shell: bash
      - name: "Build UTs"
        working-directory: ./FppTestProject/FppTest
        run: |
          fprime-util build --ut
        shell: bash
      - name: "Run UTs"
        working-directory: ./FppTestProject/FppTest
        run: |
          fprime-util check
        shell: bash
      - name: "Archive Logs"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: FppTest-Logs
          path: ./FppTestProject/build-fprime-automatic-native-ut/Testing/Temporary/*.log
          retention-days: 5
