name: Check Markdown links

on: 
  push:
    branches: [devel, docs/new-website]
  pull_request:
    branches: [devel]
# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: 'Generate Doxygen and CMake docs'
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen
        ./docs/doxygen/generate_docs.bash

    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
          use-quiet-mode: 'yes'
          config-file: ./.github/actions/markdown-check/mlc-config.json
